# controller:
#   ingressClassResource:
#     name: nginx
#     enabled: true
#     default: true
#     controllerValue: "k8s.io/ingress-nginx"
  
#   service:
#     targetPorts:
#       http: http
#       https: https
#     annotations:
#       # This tells AWS to create a Network Load Balancer (NLB) natively
#       service.beta.kubernetes.io/aws-load-balancer-type: nlb
#       # This makes it public (Internet Gateway)
#       service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
#       # Ensures the NLB spans all AZs for high availability
#       service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"


controller:
  ingressClassResource:
    name: nginx
    enabled: true
    default: true
    controllerValue: "k8s.io/ingress-nginx"
  
  service:
    # 1. CHANGE TYPE TO NODEPORT (Bypass AWS Load Balancers)
    type: NodePort
    
    # 2. DEFINE STATIC PORTS (So you know where to connect)
    nodePorts:
      http: 30080
      https: 30443
    
    # 3. REMOVE ALL AWS ANNOTATIONS (They cause errors on your account)
    annotations: {}
